# Generated by Django 5.1.2 on 2024-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngodars', '0002_premise_premisetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='merchantID',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='addressID',
        ),
        migrations.AddField(
            model_name='premise',
            name='poscode',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='premise',
            name='statearea',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='premise',
            name='streetname',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='premise',
            name='unit',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='premise',
            name='premisetype',
            field=models.TextField(choices=[('Hall', 'hall'), ('catering', 'Catering'), ('Food', 'food')], default=None),
        ),
    ]
