# Generated by Django 5.1.2 on 2024-11-17 13:32

import django.db.models.deletion
import ngodars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngodars', '0003_remove_address_merchantid_remove_premise_addressid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fullname',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='poscode',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='statearea',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='streetname',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='itemID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.item'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemimage',
            field=models.ImageField(default=None, upload_to='item_images/', validators=[ngodars.models.ITEM.validate_image]),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='premiseID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.premise'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchantname',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='userID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.user'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='merchantID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.merchant'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='premiseimage',
            field=models.ImageField(default=None, upload_to='premise_images/', validators=[ngodars.models.PREMISE.validate_image]),
        ),
        migrations.AlterField(
            model_name='premise',
            name='premisetype',
            field=models.TextField(choices=[('hall', 'Hall'), ('catering', 'Catering'), ('Food', 'food')], default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default=None),
        ),
    ]
