# Generated by Django 5.1.5 on 2025-01-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngodars', '0005_address_is_used_alter_premise_premisetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premisetype',
            field=models.TextField(choices=[('Hall', 'hall'), ('catering', 'Catering'), ('Food', 'food')], default=None),
        ),
        migrations.CreateModel(
            name='EWALLET',
            fields=[
                ('ewalletID', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngodars.user')),
            ],
        ),
    ]
